- name: add nginx repository
  apt_repository: repo="{{ nginx.repository }}"
  tags: nginx

- name: add repository key
  apt_key: url="{{ nginx.apt_key }}"
  tags: nginx

- name: install nginx
  apt: pkg=nginx update-cache=yes
  tags: nginx

- name: delete default.conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  tags: nginx

- name: copy nginx configuration
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - validate nginx
    - restart nginx
  tags: nginx

- name: copy nginx configuration for app
  template: src=templates/nginx.app.conf.j2 dest="/etc/nginx/conf.d/{{ app }}.conf"
  notify:
    - validate nginx
    - restart nginx
  tags: nginx
