- name: update ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    validate: "/usr/sbin/sshd -t -f %s"
  with_items:
    - { key: "Port",                   value: "{{ ssh.port }}"}
    - { key: "PermitRootLogin",        value: "{{ ssh.permit_root_login }}"}
    - { key: "PasswordAuthentication", value: "{{ ssh.password_authentication }}"}
  notify: restart sshd
  tags: ssh
